build:
  image: ubuntu:latest
  commands:
    - apt-get -qq update
    - apt-get -qy install software-properties-common
    - add-apt-repository -y ppa:ubuntu-elisp
    - apt-get -qq update
    - apt-get -qy install emacs-snapshot
    - emacs -nw --batch -l emacsbuild.el
 
publish:
  github_release:
    files:
      - Publish/*
    checksum: sha1
    